print('Escolha um')
print('_________________________________')
print('professor-P')
print('aluno do fundamental-EF')
print('aluno do ensino médio-EM')
print('funcionario-F')
print('_________________________________')

pergunta= input('digite uma das letras para receber as perguntas:')


Nome= str(input('Qual e o seu nome do aluno?'))
CPF= int(input('Qual e o CPF do aluno ?'))
RG= int(input('Qual e o RG do aluno?'))
número= int(input('Qual e o  número do aluno ?'))
série=input('Qual e a série ?')
print(série ,'ano do ensino médio')
período= str(input('Qual e o período de estudo :'))
print('___________________________________________')
print('Menu')
print('___________________________________________')
print('nome do aluno é:',Nome)
print('o CPF:',CPF)
print('o RG:',RG)
print('o número:',número)
print('a série:',série)
print('o período:',período)
print('___________________________________________')

print('Você esta casdastrado')

Nome= str(input('Qual e o seu nome do aluno?'))
CPF= int(input('Qual e o CPF do aluno ?'))
RG= int(input('Qual e o RG do aluno?'))
número= int(input('Qual e o  número do aluno ?'))
série=input('Qual e a série ?')
print(série ,'ano do ensino fundamental')
período= str(input('Qual e o período de estudo :'))
print('___________________________________________')
print('Menu')
print('___________________________________________')
print('nome do aluno é:',Nome)
print('o CPF:',CPF)
print('o RG:',RG)
print('o número:',número)
print('a série:',série)
print('o período:',período)
print('___________________________________________')

print('Você esta casdastrado')




Nome= str(input('Qual e o seu nome do professor?'))
CPF= int(input('Qual e o CPF do professor ?'))
RG= int(input('Qual e o RG do professor?'))
série=input('Qual e a série ?')
print(série ,'ano do ensino médio')
período= str(input('Qual e o período que dá aula :'))
print('___________________________________________')
print('Menu')
print('___________________________________________')
print('nome do professor é:',Nome)
print('o CPF:',CPF)
print('o RG:',RG)
print('o número:',número)
print('a série:',série)
print('o período:',período)
print('___________________________________________')

print('Você esta casdastrado')


Nome= str(input('Qual e o seu nome do funcionario?'))
CPF= int(input('Qual e o CPF do funcionario ?'))
RG= int(input('Qual e o RG do funcionario?'))
série=input('Qual e a série ?')
print(série ,'ano do ensino médio')
período= str(input('Qual e o período de trabalho :'))
print('___________________________________________')
print('Menu')
print('___________________________________________')
print('nome do funcionario é:',Nome)
print('o CPF:',CPF)
print('o RG:',RG)
print('o número:',número)
print('a série:',série)
print('o período:',período)
print('___________________________________________')

print('Você esta casdastrado')



